/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventTrackingTestRouteImport } from './routes/event-tracking-test'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OcrServicesIndexRouteImport } from './routes/ocr-services/index'
import { Route as OcrServicesApiDocsUsageExamplesRouteImport } from './routes/ocr-services/api-docs/usage-examples'
import { Route as OcrServicesApiDocsChangelogRouteImport } from './routes/ocr-services/api-docs/changelog'
import { Route as OcrServicesApiDocsBestPracticesRouteImport } from './routes/ocr-services/api-docs/best-practices'
import { Route as OcrServicesOrgldPriceRouteImport } from './routes/ocr-services/$orgld.price'
import { Route as OcrServicesOrgIdOverviewRouteImport } from './routes/ocr-services/$orgId.overview'
import { Route as OcrServicesOrgIdIssuesRouteImport } from './routes/ocr-services/$orgId.issues'
import { Route as OcrServicesOrgIdHomeRouteImport } from './routes/ocr-services/$orgId.home'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventTrackingTestRoute = EventTrackingTestRouteImport.update({
  id: '/event-tracking-test',
  path: '/event-tracking-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrServicesIndexRoute = OcrServicesIndexRouteImport.update({
  id: '/ocr-services/',
  path: '/ocr-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrServicesApiDocsUsageExamplesRoute =
  OcrServicesApiDocsUsageExamplesRouteImport.update({
    id: '/ocr-services/api-docs/usage-examples',
    path: '/ocr-services/api-docs/usage-examples',
    getParentRoute: () => rootRouteImport,
  } as any)
const OcrServicesApiDocsChangelogRoute =
  OcrServicesApiDocsChangelogRouteImport.update({
    id: '/ocr-services/api-docs/changelog',
    path: '/ocr-services/api-docs/changelog',
    getParentRoute: () => rootRouteImport,
  } as any)
const OcrServicesApiDocsBestPracticesRoute =
  OcrServicesApiDocsBestPracticesRouteImport.update({
    id: '/ocr-services/api-docs/best-practices',
    path: '/ocr-services/api-docs/best-practices',
    getParentRoute: () => rootRouteImport,
  } as any)
const OcrServicesOrgldPriceRoute = OcrServicesOrgldPriceRouteImport.update({
  id: '/ocr-services/$orgld/price',
  path: '/ocr-services/$orgld/price',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrServicesOrgIdOverviewRoute =
  OcrServicesOrgIdOverviewRouteImport.update({
    id: '/ocr-services/$orgId/overview',
    path: '/ocr-services/$orgId/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const OcrServicesOrgIdIssuesRoute = OcrServicesOrgIdIssuesRouteImport.update({
  id: '/ocr-services/$orgId/issues',
  path: '/ocr-services/$orgId/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrServicesOrgIdHomeRoute = OcrServicesOrgIdHomeRouteImport.update({
  id: '/ocr-services/$orgId/home',
  path: '/ocr-services/$orgId/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/event-tracking-test': typeof EventTrackingTestRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/test': typeof TestRoute
  '/ocr-services': typeof OcrServicesIndexRoute
  '/ocr-services/$orgId/home': typeof OcrServicesOrgIdHomeRoute
  '/ocr-services/$orgId/issues': typeof OcrServicesOrgIdIssuesRoute
  '/ocr-services/$orgId/overview': typeof OcrServicesOrgIdOverviewRoute
  '/ocr-services/$orgld/price': typeof OcrServicesOrgldPriceRoute
  '/ocr-services/api-docs/best-practices': typeof OcrServicesApiDocsBestPracticesRoute
  '/ocr-services/api-docs/changelog': typeof OcrServicesApiDocsChangelogRoute
  '/ocr-services/api-docs/usage-examples': typeof OcrServicesApiDocsUsageExamplesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/event-tracking-test': typeof EventTrackingTestRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/test': typeof TestRoute
  '/ocr-services': typeof OcrServicesIndexRoute
  '/ocr-services/$orgId/home': typeof OcrServicesOrgIdHomeRoute
  '/ocr-services/$orgId/issues': typeof OcrServicesOrgIdIssuesRoute
  '/ocr-services/$orgId/overview': typeof OcrServicesOrgIdOverviewRoute
  '/ocr-services/$orgld/price': typeof OcrServicesOrgldPriceRoute
  '/ocr-services/api-docs/best-practices': typeof OcrServicesApiDocsBestPracticesRoute
  '/ocr-services/api-docs/changelog': typeof OcrServicesApiDocsChangelogRoute
  '/ocr-services/api-docs/usage-examples': typeof OcrServicesApiDocsUsageExamplesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/event-tracking-test': typeof EventTrackingTestRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/test': typeof TestRoute
  '/ocr-services/': typeof OcrServicesIndexRoute
  '/ocr-services/$orgId/home': typeof OcrServicesOrgIdHomeRoute
  '/ocr-services/$orgId/issues': typeof OcrServicesOrgIdIssuesRoute
  '/ocr-services/$orgId/overview': typeof OcrServicesOrgIdOverviewRoute
  '/ocr-services/$orgld/price': typeof OcrServicesOrgldPriceRoute
  '/ocr-services/api-docs/best-practices': typeof OcrServicesApiDocsBestPracticesRoute
  '/ocr-services/api-docs/changelog': typeof OcrServicesApiDocsChangelogRoute
  '/ocr-services/api-docs/usage-examples': typeof OcrServicesApiDocsUsageExamplesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/event-tracking-test'
    | '/login'
    | '/overview'
    | '/test'
    | '/ocr-services'
    | '/ocr-services/$orgId/home'
    | '/ocr-services/$orgId/issues'
    | '/ocr-services/$orgId/overview'
    | '/ocr-services/$orgld/price'
    | '/ocr-services/api-docs/best-practices'
    | '/ocr-services/api-docs/changelog'
    | '/ocr-services/api-docs/usage-examples'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/event-tracking-test'
    | '/login'
    | '/overview'
    | '/test'
    | '/ocr-services'
    | '/ocr-services/$orgId/home'
    | '/ocr-services/$orgId/issues'
    | '/ocr-services/$orgId/overview'
    | '/ocr-services/$orgld/price'
    | '/ocr-services/api-docs/best-practices'
    | '/ocr-services/api-docs/changelog'
    | '/ocr-services/api-docs/usage-examples'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/event-tracking-test'
    | '/login'
    | '/overview'
    | '/test'
    | '/ocr-services/'
    | '/ocr-services/$orgId/home'
    | '/ocr-services/$orgId/issues'
    | '/ocr-services/$orgId/overview'
    | '/ocr-services/$orgld/price'
    | '/ocr-services/api-docs/best-practices'
    | '/ocr-services/api-docs/changelog'
    | '/ocr-services/api-docs/usage-examples'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  EventTrackingTestRoute: typeof EventTrackingTestRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  TestRoute: typeof TestRoute
  OcrServicesIndexRoute: typeof OcrServicesIndexRoute
  OcrServicesOrgIdHomeRoute: typeof OcrServicesOrgIdHomeRoute
  OcrServicesOrgIdIssuesRoute: typeof OcrServicesOrgIdIssuesRoute
  OcrServicesOrgIdOverviewRoute: typeof OcrServicesOrgIdOverviewRoute
  OcrServicesOrgldPriceRoute: typeof OcrServicesOrgldPriceRoute
  OcrServicesApiDocsBestPracticesRoute: typeof OcrServicesApiDocsBestPracticesRoute
  OcrServicesApiDocsChangelogRoute: typeof OcrServicesApiDocsChangelogRoute
  OcrServicesApiDocsUsageExamplesRoute: typeof OcrServicesApiDocsUsageExamplesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-tracking-test': {
      id: '/event-tracking-test'
      path: '/event-tracking-test'
      fullPath: '/event-tracking-test'
      preLoaderRoute: typeof EventTrackingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/': {
      id: '/ocr-services/'
      path: '/ocr-services'
      fullPath: '/ocr-services'
      preLoaderRoute: typeof OcrServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/api-docs/usage-examples': {
      id: '/ocr-services/api-docs/usage-examples'
      path: '/ocr-services/api-docs/usage-examples'
      fullPath: '/ocr-services/api-docs/usage-examples'
      preLoaderRoute: typeof OcrServicesApiDocsUsageExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/api-docs/changelog': {
      id: '/ocr-services/api-docs/changelog'
      path: '/ocr-services/api-docs/changelog'
      fullPath: '/ocr-services/api-docs/changelog'
      preLoaderRoute: typeof OcrServicesApiDocsChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/api-docs/best-practices': {
      id: '/ocr-services/api-docs/best-practices'
      path: '/ocr-services/api-docs/best-practices'
      fullPath: '/ocr-services/api-docs/best-practices'
      preLoaderRoute: typeof OcrServicesApiDocsBestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/$orgld/price': {
      id: '/ocr-services/$orgld/price'
      path: '/ocr-services/$orgld/price'
      fullPath: '/ocr-services/$orgld/price'
      preLoaderRoute: typeof OcrServicesOrgldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/$orgId/overview': {
      id: '/ocr-services/$orgId/overview'
      path: '/ocr-services/$orgId/overview'
      fullPath: '/ocr-services/$orgId/overview'
      preLoaderRoute: typeof OcrServicesOrgIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/$orgId/issues': {
      id: '/ocr-services/$orgId/issues'
      path: '/ocr-services/$orgId/issues'
      fullPath: '/ocr-services/$orgId/issues'
      preLoaderRoute: typeof OcrServicesOrgIdIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-services/$orgId/home': {
      id: '/ocr-services/$orgId/home'
      path: '/ocr-services/$orgId/home'
      fullPath: '/ocr-services/$orgId/home'
      preLoaderRoute: typeof OcrServicesOrgIdHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  EventTrackingTestRoute: EventTrackingTestRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  TestRoute: TestRoute,
  OcrServicesIndexRoute: OcrServicesIndexRoute,
  OcrServicesOrgIdHomeRoute: OcrServicesOrgIdHomeRoute,
  OcrServicesOrgIdIssuesRoute: OcrServicesOrgIdIssuesRoute,
  OcrServicesOrgIdOverviewRoute: OcrServicesOrgIdOverviewRoute,
  OcrServicesOrgldPriceRoute: OcrServicesOrgldPriceRoute,
  OcrServicesApiDocsBestPracticesRoute: OcrServicesApiDocsBestPracticesRoute,
  OcrServicesApiDocsChangelogRoute: OcrServicesApiDocsChangelogRoute,
  OcrServicesApiDocsUsageExamplesRoute: OcrServicesApiDocsUsageExamplesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
